/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 1
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_source_file_token1 = 2,
  anon_sym_import = 3,
  anon_sym_COLON_COLON = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_POUND = 8,
  sym_path_relative_prefix = 9,
  sym_path_body = 10,
  anon_sym_enum = 11,
  anon_sym_PIPE = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_COLON = 15,
  anon_sym_struct = 16,
  anon_sym_maybe = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_DOT_DOT_DOT = 20,
  sym_attribute_arg = 21,
  anon_sym_SLASH_SLASH = 22,
  aux_sym_comment_token1 = 23,
  sym_string = 24,
  sym_type_identifier = 25,
  sym_source_file = 26,
  sym__definition = 27,
  sym_import_statement = 28,
  sym_import_path = 29,
  sym_path_alias_prefix = 30,
  sym_enum_declaration = 31,
  sym_variant = 32,
  sym_variant_params = 33,
  sym_named_field = 34,
  sym_struct_declaration = 35,
  sym_struct_body = 36,
  sym_struct_field = 37,
  sym__type = 38,
  sym_maybe_type = 39,
  sym_generic_type = 40,
  sym_type_arguments = 41,
  sym_nested_struct = 42,
  sym_spread_type = 43,
  sym_attribute = 44,
  sym_comment = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_import_statement_repeat1 = 47,
  aux_sym_enum_declaration_repeat1 = 48,
  aux_sym_variant_params_repeat1 = 49,
  aux_sym_struct_body_repeat1 = 50,
  aux_sym_type_arguments_repeat1 = 51,
  aux_sym_attribute_repeat1 = 52,
  alias_sym_imported_name = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_import] = "import",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [sym_path_relative_prefix] = "path_relative_prefix",
  [sym_path_body] = "path_body",
  [anon_sym_enum] = "enum",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_maybe] = "maybe",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT_DOT_DOT] = "...",
  [sym_attribute_arg] = "attribute_arg",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_string] = "string",
  [sym_type_identifier] = "type_identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_import_statement] = "import_statement",
  [sym_import_path] = "import_path",
  [sym_path_alias_prefix] = "path_alias_prefix",
  [sym_enum_declaration] = "enum_declaration",
  [sym_variant] = "variant",
  [sym_variant_params] = "variant_params",
  [sym_named_field] = "named_field",
  [sym_struct_declaration] = "struct_declaration",
  [sym_struct_body] = "struct_body",
  [sym_struct_field] = "struct_field",
  [sym__type] = "_type",
  [sym_maybe_type] = "maybe_type",
  [sym_generic_type] = "generic_type",
  [sym_type_arguments] = "type_arguments",
  [sym_nested_struct] = "nested_struct",
  [sym_spread_type] = "spread_type",
  [sym_attribute] = "attribute",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_statement_repeat1] = "import_statement_repeat1",
  [aux_sym_enum_declaration_repeat1] = "enum_declaration_repeat1",
  [aux_sym_variant_params_repeat1] = "variant_params_repeat1",
  [aux_sym_struct_body_repeat1] = "struct_body_repeat1",
  [aux_sym_type_arguments_repeat1] = "type_arguments_repeat1",
  [aux_sym_attribute_repeat1] = "attribute_repeat1",
  [alias_sym_imported_name] = "imported_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_path_relative_prefix] = sym_path_relative_prefix,
  [sym_path_body] = sym_path_body,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_maybe] = anon_sym_maybe,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [sym_attribute_arg] = sym_attribute_arg,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_string] = sym_string,
  [sym_type_identifier] = sym_type_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_import_statement] = sym_import_statement,
  [sym_import_path] = sym_import_path,
  [sym_path_alias_prefix] = sym_path_alias_prefix,
  [sym_enum_declaration] = sym_enum_declaration,
  [sym_variant] = sym_variant,
  [sym_variant_params] = sym_variant_params,
  [sym_named_field] = sym_named_field,
  [sym_struct_declaration] = sym_struct_declaration,
  [sym_struct_body] = sym_struct_body,
  [sym_struct_field] = sym_struct_field,
  [sym__type] = sym__type,
  [sym_maybe_type] = sym_maybe_type,
  [sym_generic_type] = sym_generic_type,
  [sym_type_arguments] = sym_type_arguments,
  [sym_nested_struct] = sym_nested_struct,
  [sym_spread_type] = sym_spread_type,
  [sym_attribute] = sym_attribute,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_statement_repeat1] = aux_sym_import_statement_repeat1,
  [aux_sym_enum_declaration_repeat1] = aux_sym_enum_declaration_repeat1,
  [aux_sym_variant_params_repeat1] = aux_sym_variant_params_repeat1,
  [aux_sym_struct_body_repeat1] = aux_sym_struct_body_repeat1,
  [aux_sym_type_arguments_repeat1] = aux_sym_type_arguments_repeat1,
  [aux_sym_attribute_repeat1] = aux_sym_attribute_repeat1,
  [alias_sym_imported_name] = alias_sym_imported_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_path_relative_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_path_body] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_maybe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_path] = {
    .visible = true,
    .named = true,
  },
  [sym_path_alias_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_variant_params] = {
    .visible = true,
    .named = true,
  },
  [sym_named_field] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_maybe_type] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_spread_type] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variant_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_imported_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_path = 2,
  field_type = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_imported_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 6,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 16,
  [60] = 19,
  [61] = 18,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 72,
  [80] = 78,
  [81] = 69,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 97,
  [99] = 99,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 27,
        '\r', 1,
        '"', 4,
        '#', 35,
        '\'', 6,
        '(', 60,
        ')', 61,
        ',', 33,
        '.', 39,
        '/', 9,
        ':', 63,
        '<', 67,
        '>', 68,
        'e', 81,
        'i', 79,
        's', 86,
        '{', 32,
        '|', 59,
        '}', 34,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(27);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 27,
        '\r', 1,
        '#', 35,
        '(', 60,
        ')', 61,
        ',', 33,
        '.', 8,
        '/', 9,
        ':', 62,
        '<', 67,
        '>', 68,
        '{', 32,
        '}', 34,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == ')') ADVANCE(61);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(69);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(71);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'm') ADVANCE(56);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 24:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 27,
        '\r', 1,
        '#', 35,
        '(', 60,
        ',', 33,
        '/', 9,
        ':', 10,
        'e', 14,
        'i', 12,
        's', 19,
        '{', 32,
        '|', 59,
        '}', 34,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(24);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 27,
        '\r', 1,
        '#', 35,
        '/', 40,
        ':', 10,
        'e', 44,
        'i', 42,
        's', 49,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_import);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_import);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(69);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(37);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == '/') ADVANCE(72);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'c') ADVANCE(51);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'm') ADVANCE(46);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'm') ADVANCE(58);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'n') ADVANCE(53);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'o') ADVANCE(47);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'p') ADVANCE(45);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'r') ADVANCE(50);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'r') ADVANCE(52);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 't') ADVANCE(48);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 't') ADVANCE(30);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 't') ADVANCE(66);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'u') ADVANCE(41);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'u') ADVANCE(43);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_path_body);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_path_body);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_enum);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_enum);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(31);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_attribute_arg);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'm') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'y') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_maybe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 25},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 25},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 24},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 24},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 24},
  [49] = {.lex_state = 24},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 24},
  [52] = {.lex_state = 24},
  [53] = {.lex_state = 24},
  [54] = {.lex_state = 24},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 24},
  [57] = {.lex_state = 24},
  [58] = {.lex_state = 24},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 74},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_path_relative_prefix] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_maybe] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(90),
    [sym__definition] = STATE(48),
    [sym_import_statement] = STATE(53),
    [sym_enum_declaration] = STATE(53),
    [sym_struct_declaration] = STATE(53),
    [sym_attribute] = STATE(53),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      aux_sym_source_file_token1,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      sym__definition,
    STATE(53), 4,
      sym_import_statement,
      sym_enum_declaration,
      sym_struct_declaration,
      sym_attribute,
  [37] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      aux_sym_source_file_token1,
    ACTIONS(24), 1,
      anon_sym_import,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(30), 1,
      anon_sym_enum,
    ACTIONS(33), 1,
      anon_sym_struct,
    STATE(48), 1,
      sym__definition,
    STATE(3), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(53), 4,
      sym_import_statement,
      sym_enum_declaration,
      sym_struct_declaration,
      sym_attribute,
  [72] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 1,
      anon_sym_maybe,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(4), 1,
      sym_comment,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
    STATE(73), 3,
      sym_named_field,
      sym__type,
      sym_spread_type,
  [107] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_maybe,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(5), 1,
      sym_comment,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
    STATE(84), 3,
      sym_named_field,
      sym__type,
      sym_spread_type,
  [139] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_comment,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [160] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    ACTIONS(58), 1,
      anon_sym_POUND,
    STATE(7), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(54), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(50), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [191] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_import_statement_repeat1,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(64), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    ACTIONS(66), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [220] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(54), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(50), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [251] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      anon_sym_POUND,
    ACTIONS(83), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(75), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(10), 2,
      sym_comment,
      aux_sym_struct_body_repeat1,
    STATE(50), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [280] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(91), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(11), 2,
      sym_comment,
      aux_sym_import_statement_repeat1,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUND,
    ACTIONS(94), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [305] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(98), 1,
      anon_sym_LT,
    STATE(12), 1,
      sym_comment,
    STATE(21), 1,
      sym_type_arguments,
    ACTIONS(96), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [328] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      aux_sym_import_statement_repeat1,
    STATE(13), 1,
      sym_comment,
    ACTIONS(64), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(102), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [357] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(54), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(50), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [388] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_POUND,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      aux_sym_struct_body_repeat1,
    STATE(15), 1,
      sym_comment,
    ACTIONS(54), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(50), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [419] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(110), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [437] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(114), 4,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
  [457] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(116), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [475] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [493] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(122), 4,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
  [513] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(124), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [530] = 4,
    ACTIONS(130), 1,
      anon_sym_SLASH_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
    ACTIONS(128), 4,
      anon_sym_import,
      sym_path_body,
      anon_sym_enum,
      anon_sym_struct,
  [549] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      sym_comment,
    STATE(35), 1,
      aux_sym_enum_declaration_repeat1,
    ACTIONS(132), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(63), 2,
      sym_variant,
      sym_attribute,
  [576] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      sym_comment,
    STATE(47), 1,
      sym_variant_params,
    STATE(68), 1,
      sym_attribute,
    ACTIONS(138), 4,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [601] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    ACTIONS(147), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(142), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(25), 2,
      sym_comment,
      aux_sym_enum_declaration_repeat1,
    STATE(63), 2,
      sym_variant,
      sym_attribute,
  [626] = 5,
    ACTIONS(130), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(157), 1,
      sym_path_body,
    STATE(26), 1,
      sym_comment,
    ACTIONS(155), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
  [647] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(96), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [664] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(159), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [681] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(161), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [698] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(163), 1,
      anon_sym_maybe,
    ACTIONS(165), 1,
      anon_sym_GT,
    STATE(30), 1,
      sym_comment,
    STATE(70), 1,
      sym__type,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [725] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(167), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [742] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(169), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [759] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(171), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [776] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(173), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [793] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(136), 1,
      anon_sym_PIPE,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_enum_declaration_repeat1,
    STATE(35), 1,
      sym_comment,
    ACTIONS(132), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(63), 2,
      sym_variant,
      sym_attribute,
  [820] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(177), 7,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [836] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [852] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_COLON_COLON,
    STATE(38), 1,
      sym_comment,
    ACTIONS(179), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [870] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(58), 1,
      anon_sym_POUND,
    STATE(39), 1,
      sym_comment,
    STATE(55), 1,
      sym_attribute,
    ACTIONS(183), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [890] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(187), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_comment,
    ACTIONS(185), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [908] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(163), 1,
      anon_sym_maybe,
    STATE(29), 1,
      sym__type,
    STATE(41), 1,
      sym_comment,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [932] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(42), 1,
      sym_comment,
    ACTIONS(189), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [948] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(163), 1,
      anon_sym_maybe,
    STATE(39), 1,
      sym__type,
    STATE(43), 1,
      sym_comment,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [972] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(163), 1,
      anon_sym_maybe,
    STATE(44), 1,
      sym_comment,
    STATE(87), 1,
      sym__type,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [996] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(163), 1,
      anon_sym_maybe,
    STATE(45), 1,
      sym_comment,
    STATE(83), 1,
      sym__type,
    STATE(27), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1020] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(191), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_comment,
    ACTIONS(48), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1038] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    STATE(47), 1,
      sym_comment,
    STATE(65), 1,
      sym_attribute,
    ACTIONS(193), 4,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1057] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(195), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1072] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(197), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1087] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(199), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1102] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(201), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1117] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(203), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1132] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(205), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1147] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(207), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1162] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(55), 1,
      sym_comment,
    ACTIONS(209), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1177] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(211), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1192] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(213), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1207] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1222] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(110), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1237] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(118), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1252] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(116), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1267] = 7,
    ACTIONS(130), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(215), 1,
      anon_sym_POUND,
    ACTIONS(217), 1,
      sym_path_relative_prefix,
    ACTIONS(219), 1,
      sym_path_body,
    STATE(26), 1,
      sym_path_alias_prefix,
    STATE(38), 1,
      sym_import_path,
    STATE(62), 1,
      sym_comment,
  [1289] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(221), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1303] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(223), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1317] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(225), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1331] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(66), 1,
      sym_comment,
    ACTIONS(227), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1345] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(67), 1,
      sym_comment,
    ACTIONS(229), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1359] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(193), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1373] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_comment,
    STATE(75), 1,
      aux_sym_attribute_repeat1,
  [1389] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_GT,
    STATE(70), 1,
      sym_comment,
    STATE(76), 1,
      aux_sym_type_arguments_repeat1,
  [1405] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym_comment,
    STATE(74), 1,
      aux_sym_variant_params_repeat1,
  [1421] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      sym_comment,
    ACTIONS(245), 2,
      sym_attribute_arg,
      sym_string,
  [1435] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_variant_params_repeat1,
    STATE(73), 1,
      sym_comment,
  [1451] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(74), 2,
      sym_comment,
      aux_sym_variant_params_repeat1,
  [1465] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(75), 2,
      sym_comment,
      aux_sym_attribute_repeat1,
  [1479] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_GT,
    STATE(76), 1,
      sym_comment,
    STATE(77), 1,
      aux_sym_type_arguments_repeat1,
  [1495] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_GT,
    STATE(77), 2,
      sym_comment,
      aux_sym_type_arguments_repeat1,
  [1509] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_attribute_repeat1,
    STATE(78), 1,
      sym_comment,
  [1525] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      sym_comment,
    ACTIONS(270), 2,
      sym_attribute_arg,
      sym_string,
  [1539] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_comment,
    STATE(81), 1,
      aux_sym_attribute_repeat1,
  [1555] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_attribute_repeat1,
    STATE(81), 1,
      sym_comment,
  [1571] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(82), 1,
      sym_comment,
    ACTIONS(257), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1582] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(83), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1593] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(84), 1,
      sym_comment,
    ACTIONS(252), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1604] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(85), 1,
      sym_comment,
    ACTIONS(278), 2,
      sym_attribute_arg,
      sym_string,
  [1615] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_struct_body,
    STATE(86), 1,
      sym_comment,
  [1628] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(87), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1639] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(282), 1,
      sym_type_identifier,
    STATE(88), 1,
      sym_comment,
  [1649] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(284), 1,
      sym_type_identifier,
    STATE(89), 1,
      sym_comment,
  [1659] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
    STATE(90), 1,
      sym_comment,
  [1669] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(288), 1,
      sym_type_identifier,
    STATE(91), 1,
      sym_comment,
  [1679] = 3,
    ACTIONS(130), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(290), 1,
      aux_sym_comment_token1,
    STATE(92), 1,
      sym_comment,
  [1689] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(292), 1,
      anon_sym_COLON,
    STATE(93), 1,
      sym_comment,
  [1699] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(294), 1,
      sym_type_identifier,
    STATE(94), 1,
      sym_comment,
  [1709] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(296), 1,
      anon_sym_COLON,
    STATE(95), 1,
      sym_comment,
  [1719] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(298), 1,
      anon_sym_LBRACE,
    STATE(96), 1,
      sym_comment,
  [1729] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(300), 1,
      sym_identifier,
    STATE(97), 1,
      sym_comment,
  [1739] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(302), 1,
      sym_identifier,
    STATE(98), 1,
      sym_comment,
  [1749] = 1,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 191,
  [SMALL_STATE(9)] = 220,
  [SMALL_STATE(10)] = 251,
  [SMALL_STATE(11)] = 280,
  [SMALL_STATE(12)] = 305,
  [SMALL_STATE(13)] = 328,
  [SMALL_STATE(14)] = 357,
  [SMALL_STATE(15)] = 388,
  [SMALL_STATE(16)] = 419,
  [SMALL_STATE(17)] = 437,
  [SMALL_STATE(18)] = 457,
  [SMALL_STATE(19)] = 475,
  [SMALL_STATE(20)] = 493,
  [SMALL_STATE(21)] = 513,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 549,
  [SMALL_STATE(24)] = 576,
  [SMALL_STATE(25)] = 601,
  [SMALL_STATE(26)] = 626,
  [SMALL_STATE(27)] = 647,
  [SMALL_STATE(28)] = 664,
  [SMALL_STATE(29)] = 681,
  [SMALL_STATE(30)] = 698,
  [SMALL_STATE(31)] = 725,
  [SMALL_STATE(32)] = 742,
  [SMALL_STATE(33)] = 759,
  [SMALL_STATE(34)] = 776,
  [SMALL_STATE(35)] = 793,
  [SMALL_STATE(36)] = 820,
  [SMALL_STATE(37)] = 836,
  [SMALL_STATE(38)] = 852,
  [SMALL_STATE(39)] = 870,
  [SMALL_STATE(40)] = 890,
  [SMALL_STATE(41)] = 908,
  [SMALL_STATE(42)] = 932,
  [SMALL_STATE(43)] = 948,
  [SMALL_STATE(44)] = 972,
  [SMALL_STATE(45)] = 996,
  [SMALL_STATE(46)] = 1020,
  [SMALL_STATE(47)] = 1038,
  [SMALL_STATE(48)] = 1057,
  [SMALL_STATE(49)] = 1072,
  [SMALL_STATE(50)] = 1087,
  [SMALL_STATE(51)] = 1102,
  [SMALL_STATE(52)] = 1117,
  [SMALL_STATE(53)] = 1132,
  [SMALL_STATE(54)] = 1147,
  [SMALL_STATE(55)] = 1162,
  [SMALL_STATE(56)] = 1177,
  [SMALL_STATE(57)] = 1192,
  [SMALL_STATE(58)] = 1207,
  [SMALL_STATE(59)] = 1222,
  [SMALL_STATE(60)] = 1237,
  [SMALL_STATE(61)] = 1252,
  [SMALL_STATE(62)] = 1267,
  [SMALL_STATE(63)] = 1289,
  [SMALL_STATE(64)] = 1303,
  [SMALL_STATE(65)] = 1317,
  [SMALL_STATE(66)] = 1331,
  [SMALL_STATE(67)] = 1345,
  [SMALL_STATE(68)] = 1359,
  [SMALL_STATE(69)] = 1373,
  [SMALL_STATE(70)] = 1389,
  [SMALL_STATE(71)] = 1405,
  [SMALL_STATE(72)] = 1421,
  [SMALL_STATE(73)] = 1435,
  [SMALL_STATE(74)] = 1451,
  [SMALL_STATE(75)] = 1465,
  [SMALL_STATE(76)] = 1479,
  [SMALL_STATE(77)] = 1495,
  [SMALL_STATE(78)] = 1509,
  [SMALL_STATE(79)] = 1525,
  [SMALL_STATE(80)] = 1539,
  [SMALL_STATE(81)] = 1555,
  [SMALL_STATE(82)] = 1571,
  [SMALL_STATE(83)] = 1582,
  [SMALL_STATE(84)] = 1593,
  [SMALL_STATE(85)] = 1604,
  [SMALL_STATE(86)] = 1615,
  [SMALL_STATE(87)] = 1628,
  [SMALL_STATE(88)] = 1639,
  [SMALL_STATE(89)] = 1649,
  [SMALL_STATE(90)] = 1659,
  [SMALL_STATE(91)] = 1669,
  [SMALL_STATE(92)] = 1679,
  [SMALL_STATE(93)] = 1689,
  [SMALL_STATE(94)] = 1699,
  [SMALL_STATE(95)] = 1709,
  [SMALL_STATE(96)] = 1719,
  [SMALL_STATE(97)] = 1729,
  [SMALL_STATE(98)] = 1739,
  [SMALL_STATE(99)] = 1749,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 4, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 6, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 3),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_alias_prefix, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_alias_prefix, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 2, 0, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_path, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_path, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_struct, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_maybe_type, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_struct, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread_type, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 2, 0, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 4),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_path, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 3, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_declaration, 5, 0, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_declaration, 4, 0, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_declaration, 3, 0, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, 0, 4),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 4, 0, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 3, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 4, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variant_params_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variant_params_repeat1, 2, 0, 0),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_repeat1, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_field, 3, 0, 4),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [286] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lume(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lume",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
