/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 1
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_source_file_token1 = 2,
  anon_sym_import = 3,
  anon_sym_COLON_COLON = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_POUND = 8,
  sym_path_relative_prefix = 9,
  sym_path_body = 10,
  anon_sym_enum = 11,
  anon_sym_PIPE = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_COLON = 15,
  anon_sym_struct = 16,
  anon_sym_maybe = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_DOT_DOT_DOT = 20,
  sym_attribute_arg = 21,
  anon_sym_SLASH_SLASH = 22,
  aux_sym_comment_token1 = 23,
  sym_string = 24,
  sym_type_identifier = 25,
  sym_source_file = 26,
  sym__definition = 27,
  sym_import_statement = 28,
  sym_import_path = 29,
  sym_path_alias_prefix = 30,
  sym_enum_declaration = 31,
  sym_variant = 32,
  sym_variant_params = 33,
  sym_named_field = 34,
  sym_struct_declaration = 35,
  sym_struct_body = 36,
  sym_struct_field = 37,
  sym__type = 38,
  sym_maybe_type = 39,
  sym_generic_type = 40,
  sym_type_arguments = 41,
  sym_nested_struct = 42,
  sym_spread_type = 43,
  sym_attribute = 44,
  sym_comment = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_import_statement_repeat1 = 47,
  aux_sym_enum_declaration_repeat1 = 48,
  aux_sym_variant_params_repeat1 = 49,
  aux_sym_struct_body_repeat1 = 50,
  aux_sym_type_arguments_repeat1 = 51,
  aux_sym_attribute_repeat1 = 52,
  alias_sym_imported_name = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_import] = "import",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [sym_path_relative_prefix] = "path_relative_prefix",
  [sym_path_body] = "path_body",
  [anon_sym_enum] = "enum",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_maybe] = "maybe",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT_DOT_DOT] = "...",
  [sym_attribute_arg] = "attribute_arg",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_string] = "string",
  [sym_type_identifier] = "type_identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_import_statement] = "import_statement",
  [sym_import_path] = "import_path",
  [sym_path_alias_prefix] = "path_alias_prefix",
  [sym_enum_declaration] = "enum_declaration",
  [sym_variant] = "variant",
  [sym_variant_params] = "variant_params",
  [sym_named_field] = "named_field",
  [sym_struct_declaration] = "struct_declaration",
  [sym_struct_body] = "struct_body",
  [sym_struct_field] = "struct_field",
  [sym__type] = "_type",
  [sym_maybe_type] = "maybe_type",
  [sym_generic_type] = "generic_type",
  [sym_type_arguments] = "type_arguments",
  [sym_nested_struct] = "nested_struct",
  [sym_spread_type] = "spread_type",
  [sym_attribute] = "attribute",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_statement_repeat1] = "import_statement_repeat1",
  [aux_sym_enum_declaration_repeat1] = "enum_declaration_repeat1",
  [aux_sym_variant_params_repeat1] = "variant_params_repeat1",
  [aux_sym_struct_body_repeat1] = "struct_body_repeat1",
  [aux_sym_type_arguments_repeat1] = "type_arguments_repeat1",
  [aux_sym_attribute_repeat1] = "attribute_repeat1",
  [alias_sym_imported_name] = "imported_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_path_relative_prefix] = sym_path_relative_prefix,
  [sym_path_body] = sym_path_body,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_maybe] = anon_sym_maybe,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [sym_attribute_arg] = sym_attribute_arg,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_string] = sym_string,
  [sym_type_identifier] = sym_type_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_import_statement] = sym_import_statement,
  [sym_import_path] = sym_import_path,
  [sym_path_alias_prefix] = sym_path_alias_prefix,
  [sym_enum_declaration] = sym_enum_declaration,
  [sym_variant] = sym_variant,
  [sym_variant_params] = sym_variant_params,
  [sym_named_field] = sym_named_field,
  [sym_struct_declaration] = sym_struct_declaration,
  [sym_struct_body] = sym_struct_body,
  [sym_struct_field] = sym_struct_field,
  [sym__type] = sym__type,
  [sym_maybe_type] = sym_maybe_type,
  [sym_generic_type] = sym_generic_type,
  [sym_type_arguments] = sym_type_arguments,
  [sym_nested_struct] = sym_nested_struct,
  [sym_spread_type] = sym_spread_type,
  [sym_attribute] = sym_attribute,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_statement_repeat1] = aux_sym_import_statement_repeat1,
  [aux_sym_enum_declaration_repeat1] = aux_sym_enum_declaration_repeat1,
  [aux_sym_variant_params_repeat1] = aux_sym_variant_params_repeat1,
  [aux_sym_struct_body_repeat1] = aux_sym_struct_body_repeat1,
  [aux_sym_type_arguments_repeat1] = aux_sym_type_arguments_repeat1,
  [aux_sym_attribute_repeat1] = aux_sym_attribute_repeat1,
  [alias_sym_imported_name] = alias_sym_imported_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_path_relative_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_path_body] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_maybe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_path] = {
    .visible = true,
    .named = true,
  },
  [sym_path_alias_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_variant_params] = {
    .visible = true,
    .named = true,
  },
  [sym_named_field] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_maybe_type] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_spread_type] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variant_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_imported_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_path = 2,
  field_type = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_imported_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 22,
  [49] = 6,
  [50] = 22,
  [51] = 51,
  [52] = 21,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 19,
  [64] = 20,
  [65] = 18,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 75,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 78,
  [89] = 74,
  [90] = 87,
  [91] = 85,
  [92] = 86,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '"', 76,
        '#', 33,
        '\'', 77,
        '(', 58,
        ')', 59,
        ',', 31,
        '.', 37,
        '/', 7,
        ':', 61,
        '<', 65,
        '>', 66,
        'e', 81,
        'i', 79,
        's', 86,
        '{', 30,
        '|', 57,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '#', 33,
        '(', 58,
        ')', 59,
        ',', 31,
        '.', 6,
        '/', 7,
        ':', 60,
        '<', 65,
        '>', 66,
        '{', 30,
        '|', 57,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(76);
      if (lookahead == '\'') ADVANCE(77);
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(67);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(69);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(54);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '#', 33,
        '(', 58,
        ',', 31,
        '/', 7,
        ':', 8,
        'e', 12,
        'i', 10,
        's', 17,
        '{', 30,
        '|', 57,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(22);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '#', 33,
        '/', 38,
        ':', 8,
        'e', 42,
        'i', 40,
        's', 47,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_import);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_import);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(67);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(34);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == '/') ADVANCE(70);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'c') ADVANCE(49);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'm') ADVANCE(44);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'm') ADVANCE(56);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'n') ADVANCE(51);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'o') ADVANCE(45);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'p') ADVANCE(43);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'r') ADVANCE(48);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'r') ADVANCE(50);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 't') ADVANCE(46);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 't') ADVANCE(28);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 't') ADVANCE(64);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'u') ADVANCE(39);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_path_body);
      if (lookahead == 'u') ADVANCE(41);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_path_body);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_path_body);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_enum);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_enum);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(29);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_attribute_arg);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'm') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'y') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_maybe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 23},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 22},
  [40] = {.lex_state = 22},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 22},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 22},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 22},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 22},
  [54] = {.lex_state = 22},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 22},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 22},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 22},
  [61] = {.lex_state = 22},
  [62] = {.lex_state = 22},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 22},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 72},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_path_relative_prefix] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_maybe] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(105),
    [sym__definition] = STATE(62),
    [sym_import_statement] = STATE(61),
    [sym_enum_declaration] = STATE(61),
    [sym_struct_declaration] = STATE(61),
    [sym_attribute] = STATE(61),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      aux_sym_source_file_token1,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      sym__definition,
    STATE(61), 4,
      sym_import_statement,
      sym_enum_declaration,
      sym_struct_declaration,
      sym_attribute,
  [37] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      aux_sym_source_file_token1,
    ACTIONS(24), 1,
      anon_sym_import,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(30), 1,
      anon_sym_enum,
    ACTIONS(33), 1,
      anon_sym_struct,
    STATE(62), 1,
      sym__definition,
    STATE(3), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(61), 4,
      sym_import_statement,
      sym_enum_declaration,
      sym_struct_declaration,
      sym_attribute,
  [72] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 1,
      anon_sym_maybe,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(4), 1,
      sym_comment,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
    STATE(76), 3,
      sym_named_field,
      sym__type,
      sym_spread_type,
  [107] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_maybe,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(5), 1,
      sym_comment,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
    STATE(96), 3,
      sym_named_field,
      sym__type,
      sym_spread_type,
  [139] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(50), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_comment,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [160] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 1,
      anon_sym_POUND,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(55), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(7), 2,
      sym_comment,
      aux_sym_struct_body_repeat1,
    STATE(57), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [189] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 1,
      anon_sym_POUND,
    STATE(8), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(68), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(57), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [220] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_import_statement_repeat1,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(78), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    ACTIONS(80), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [249] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(89), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(10), 2,
      sym_comment,
      aux_sym_import_statement_repeat1,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUND,
    ACTIONS(92), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [274] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_struct_body_repeat1,
    STATE(11), 1,
      sym_comment,
    ACTIONS(68), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(57), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [305] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      aux_sym_import_statement_repeat1,
    STATE(12), 1,
      sym_comment,
    ACTIONS(78), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(98), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [334] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(68), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(57), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [365] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(106), 1,
      anon_sym_LT,
    STATE(14), 1,
      sym_comment,
    STATE(33), 1,
      sym_type_arguments,
    ACTIONS(104), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [388] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_struct_body_repeat1,
    STATE(15), 1,
      sym_comment,
    ACTIONS(68), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(57), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [419] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(112), 4,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
  [439] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(116), 4,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
  [459] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [477] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(120), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [495] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(122), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [513] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(124), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [531] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(128), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_comment,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_POUND,
    ACTIONS(130), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [554] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      anon_sym_POUND,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(134), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(23), 2,
      sym_comment,
      aux_sym_enum_declaration_repeat1,
    STATE(73), 2,
      sym_variant,
      sym_attribute,
  [579] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(151), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      aux_sym_enum_declaration_repeat1,
    STATE(24), 1,
      sym_comment,
    ACTIONS(145), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(73), 2,
      sym_variant,
      sym_attribute,
  [606] = 5,
    ACTIONS(157), 1,
      sym_path_body,
    ACTIONS(159), 1,
      anon_sym_SLASH_SLASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(155), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
  [627] = 4,
    ACTIONS(159), 1,
      anon_sym_SLASH_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(161), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
    ACTIONS(163), 4,
      anon_sym_import,
      sym_path_body,
      anon_sym_enum,
      anon_sym_struct,
  [646] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(151), 1,
      anon_sym_PIPE,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_enum_declaration_repeat1,
    STATE(27), 1,
      sym_comment,
    ACTIONS(145), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(73), 2,
      sym_variant,
      sym_attribute,
  [673] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(104), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [690] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(167), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [707] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(171), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_comment,
    STATE(55), 1,
      sym_variant_params,
    STATE(72), 1,
      sym_attribute,
    ACTIONS(169), 4,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [732] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(173), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [749] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(175), 1,
      anon_sym_maybe,
    ACTIONS(177), 1,
      anon_sym_GT,
    STATE(32), 1,
      sym_comment,
    STATE(79), 1,
      sym__type,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [776] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(179), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [793] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(181), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [810] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(183), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [827] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(185), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [844] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(187), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [861] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(175), 1,
      anon_sym_maybe,
    STATE(38), 1,
      sym_comment,
    STATE(44), 1,
      sym__type,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [885] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(39), 1,
      sym_comment,
    ACTIONS(189), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [901] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [917] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(175), 1,
      anon_sym_maybe,
    STATE(31), 1,
      sym__type,
    STATE(41), 1,
      sym_comment,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [941] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(42), 1,
      sym_comment,
    ACTIONS(191), 7,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [957] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(195), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_comment,
    ACTIONS(193), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [975] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(72), 1,
      anon_sym_POUND,
    STATE(44), 1,
      sym_comment,
    STATE(59), 1,
      sym_attribute,
    ACTIONS(197), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [995] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(175), 1,
      anon_sym_maybe,
    STATE(45), 1,
      sym_comment,
    STATE(97), 1,
      sym__type,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1019] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(201), 1,
      anon_sym_COLON_COLON,
    STATE(46), 1,
      sym_comment,
    ACTIONS(199), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1037] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(175), 1,
      anon_sym_maybe,
    STATE(47), 1,
      sym_comment,
    STATE(98), 1,
      sym__type,
    STATE(28), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1061] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(48), 1,
      sym_comment,
    ACTIONS(126), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1081] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_comment,
    ACTIONS(48), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1099] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_comment,
    ACTIONS(126), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
  [1119] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(211), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1134] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(124), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1149] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(213), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1164] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(215), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1179] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_comment,
    STATE(69), 1,
      sym_attribute,
    ACTIONS(217), 4,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1198] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(219), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1213] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(221), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1228] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(223), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1243] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(225), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1258] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(96), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1273] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(227), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1288] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(229), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1303] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(120), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1318] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(122), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1333] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(118), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1348] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(66), 1,
      sym_comment,
    ACTIONS(231), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1363] = 7,
    ACTIONS(159), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(233), 1,
      anon_sym_POUND,
    ACTIONS(235), 1,
      sym_path_relative_prefix,
    ACTIONS(237), 1,
      sym_path_body,
    STATE(25), 1,
      sym_path_alias_prefix,
    STATE(46), 1,
      sym_import_path,
    STATE(67), 1,
      sym_comment,
  [1385] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(239), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1399] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(241), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1413] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(70), 1,
      sym_comment,
    ACTIONS(243), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1427] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(71), 1,
      sym_comment,
    ACTIONS(245), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1441] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(72), 1,
      sym_comment,
    ACTIONS(217), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1455] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(73), 1,
      sym_comment,
    ACTIONS(247), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1469] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_attribute_repeat1,
  [1485] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym_comment,
    STATE(83), 1,
      aux_sym_attribute_repeat1,
  [1501] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_comment,
    STATE(77), 1,
      aux_sym_variant_params_repeat1,
  [1517] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym_comment,
    STATE(80), 1,
      aux_sym_variant_params_repeat1,
  [1533] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_comment,
    ACTIONS(263), 2,
      sym_attribute_arg,
      sym_string,
  [1547] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_GT,
    STATE(79), 1,
      sym_comment,
    STATE(81), 1,
      aux_sym_type_arguments_repeat1,
  [1563] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(80), 2,
      sym_comment,
      aux_sym_variant_params_repeat1,
  [1577] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_GT,
    STATE(81), 1,
      sym_comment,
    STATE(82), 1,
      aux_sym_type_arguments_repeat1,
  [1593] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_GT,
    STATE(82), 2,
      sym_comment,
      aux_sym_type_arguments_repeat1,
  [1607] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    STATE(83), 2,
      sym_comment,
      aux_sym_attribute_repeat1,
  [1621] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_attribute_repeat1,
    STATE(84), 1,
      sym_comment,
  [1637] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_attribute_repeat1,
    STATE(85), 1,
      sym_comment,
  [1653] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_attribute_repeat1,
    STATE(86), 1,
      sym_comment,
  [1669] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      sym_comment,
    ACTIONS(290), 2,
      sym_attribute_arg,
      sym_string,
  [1683] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_comment,
    ACTIONS(294), 2,
      sym_attribute_arg,
      sym_string,
  [1697] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_comment,
    STATE(91), 1,
      aux_sym_attribute_repeat1,
  [1713] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_comment,
    ACTIONS(298), 2,
      sym_attribute_arg,
      sym_string,
  [1727] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_attribute_repeat1,
    STATE(91), 1,
      sym_comment,
  [1743] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_attribute_repeat1,
    STATE(92), 1,
      sym_comment,
  [1759] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(93), 1,
      sym_comment,
    ACTIONS(284), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1770] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(94), 1,
      sym_comment,
    ACTIONS(302), 2,
      sym_attribute_arg,
      sym_string,
  [1781] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_struct_body,
    STATE(95), 1,
      sym_comment,
  [1794] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(96), 1,
      sym_comment,
    ACTIONS(272), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1805] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(97), 1,
      sym_comment,
    ACTIONS(306), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1816] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(98), 1,
      sym_comment,
    ACTIONS(279), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1827] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(308), 1,
      sym_type_identifier,
    STATE(99), 1,
      sym_comment,
  [1837] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(310), 1,
      anon_sym_LBRACE,
    STATE(100), 1,
      sym_comment,
  [1847] = 3,
    ACTIONS(159), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(312), 1,
      aux_sym_comment_token1,
    STATE(101), 1,
      sym_comment,
  [1857] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(314), 1,
      anon_sym_COLON,
    STATE(102), 1,
      sym_comment,
  [1867] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(316), 1,
      sym_type_identifier,
    STATE(103), 1,
      sym_comment,
  [1877] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(318), 1,
      anon_sym_COLON,
    STATE(104), 1,
      sym_comment,
  [1887] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(320), 1,
      ts_builtin_sym_end,
    STATE(105), 1,
      sym_comment,
  [1897] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(322), 1,
      sym_type_identifier,
    STATE(106), 1,
      sym_comment,
  [1907] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(324), 1,
      sym_type_identifier,
    STATE(107), 1,
      sym_comment,
  [1917] = 1,
    ACTIONS(326), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 189,
  [SMALL_STATE(9)] = 220,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 274,
  [SMALL_STATE(12)] = 305,
  [SMALL_STATE(13)] = 334,
  [SMALL_STATE(14)] = 365,
  [SMALL_STATE(15)] = 388,
  [SMALL_STATE(16)] = 419,
  [SMALL_STATE(17)] = 439,
  [SMALL_STATE(18)] = 459,
  [SMALL_STATE(19)] = 477,
  [SMALL_STATE(20)] = 495,
  [SMALL_STATE(21)] = 513,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 554,
  [SMALL_STATE(24)] = 579,
  [SMALL_STATE(25)] = 606,
  [SMALL_STATE(26)] = 627,
  [SMALL_STATE(27)] = 646,
  [SMALL_STATE(28)] = 673,
  [SMALL_STATE(29)] = 690,
  [SMALL_STATE(30)] = 707,
  [SMALL_STATE(31)] = 732,
  [SMALL_STATE(32)] = 749,
  [SMALL_STATE(33)] = 776,
  [SMALL_STATE(34)] = 793,
  [SMALL_STATE(35)] = 810,
  [SMALL_STATE(36)] = 827,
  [SMALL_STATE(37)] = 844,
  [SMALL_STATE(38)] = 861,
  [SMALL_STATE(39)] = 885,
  [SMALL_STATE(40)] = 901,
  [SMALL_STATE(41)] = 917,
  [SMALL_STATE(42)] = 941,
  [SMALL_STATE(43)] = 957,
  [SMALL_STATE(44)] = 975,
  [SMALL_STATE(45)] = 995,
  [SMALL_STATE(46)] = 1019,
  [SMALL_STATE(47)] = 1037,
  [SMALL_STATE(48)] = 1061,
  [SMALL_STATE(49)] = 1081,
  [SMALL_STATE(50)] = 1099,
  [SMALL_STATE(51)] = 1119,
  [SMALL_STATE(52)] = 1134,
  [SMALL_STATE(53)] = 1149,
  [SMALL_STATE(54)] = 1164,
  [SMALL_STATE(55)] = 1179,
  [SMALL_STATE(56)] = 1198,
  [SMALL_STATE(57)] = 1213,
  [SMALL_STATE(58)] = 1228,
  [SMALL_STATE(59)] = 1243,
  [SMALL_STATE(60)] = 1258,
  [SMALL_STATE(61)] = 1273,
  [SMALL_STATE(62)] = 1288,
  [SMALL_STATE(63)] = 1303,
  [SMALL_STATE(64)] = 1318,
  [SMALL_STATE(65)] = 1333,
  [SMALL_STATE(66)] = 1348,
  [SMALL_STATE(67)] = 1363,
  [SMALL_STATE(68)] = 1385,
  [SMALL_STATE(69)] = 1399,
  [SMALL_STATE(70)] = 1413,
  [SMALL_STATE(71)] = 1427,
  [SMALL_STATE(72)] = 1441,
  [SMALL_STATE(73)] = 1455,
  [SMALL_STATE(74)] = 1469,
  [SMALL_STATE(75)] = 1485,
  [SMALL_STATE(76)] = 1501,
  [SMALL_STATE(77)] = 1517,
  [SMALL_STATE(78)] = 1533,
  [SMALL_STATE(79)] = 1547,
  [SMALL_STATE(80)] = 1563,
  [SMALL_STATE(81)] = 1577,
  [SMALL_STATE(82)] = 1593,
  [SMALL_STATE(83)] = 1607,
  [SMALL_STATE(84)] = 1621,
  [SMALL_STATE(85)] = 1637,
  [SMALL_STATE(86)] = 1653,
  [SMALL_STATE(87)] = 1669,
  [SMALL_STATE(88)] = 1683,
  [SMALL_STATE(89)] = 1697,
  [SMALL_STATE(90)] = 1713,
  [SMALL_STATE(91)] = 1727,
  [SMALL_STATE(92)] = 1743,
  [SMALL_STATE(93)] = 1759,
  [SMALL_STATE(94)] = 1770,
  [SMALL_STATE(95)] = 1781,
  [SMALL_STATE(96)] = 1794,
  [SMALL_STATE(97)] = 1805,
  [SMALL_STATE(98)] = 1816,
  [SMALL_STATE(99)] = 1827,
  [SMALL_STATE(100)] = 1837,
  [SMALL_STATE(101)] = 1847,
  [SMALL_STATE(102)] = 1857,
  [SMALL_STATE(103)] = 1867,
  [SMALL_STATE(104)] = 1877,
  [SMALL_STATE(105)] = 1887,
  [SMALL_STATE(106)] = 1897,
  [SMALL_STATE(107)] = 1907,
  [SMALL_STATE(108)] = 1917,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 4, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 6, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_path, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_path, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_alias_prefix, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_alias_prefix, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_struct, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 2, 0, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_maybe_type, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, 0, 5),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_struct, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 4, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_path, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread_type, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 2, 0, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_declaration, 3, 0, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 3, 0, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_declaration, 4, 0, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, 0, 4),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_declaration, 5, 0, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 4, 0, 2),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 4, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variant_params_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variant_params_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2, 0, 0),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_repeat1, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_field, 3, 0, 4),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [320] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lume(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lume",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
