/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 1
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_source_file_token1 = 2,
  anon_sym_import = 3,
  anon_sym_COLON_COLON = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_POUND = 8,
  sym_path_relative_prefix = 9,
  anon_sym_SLASH = 10,
  sym_path_segment = 11,
  anon_sym_enum = 12,
  anon_sym_PIPE = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_COLON = 16,
  anon_sym_struct = 17,
  anon_sym_maybe = 18,
  anon_sym_LT = 19,
  anon_sym_GT = 20,
  anon_sym_DOT_DOT_DOT = 21,
  sym_attribute_arg = 22,
  anon_sym_SLASH_SLASH = 23,
  aux_sym_comment_token1 = 24,
  sym_string = 25,
  sym_type_identifier = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym_import_statement = 29,
  sym_import_path = 30,
  sym_path_alias_prefix = 31,
  sym_path_body = 32,
  sym_enum_declaration = 33,
  sym_variant = 34,
  sym_variant_params = 35,
  sym_named_field = 36,
  sym_struct_declaration = 37,
  sym_struct_body = 38,
  sym_struct_field = 39,
  sym__type = 40,
  sym_maybe_type = 41,
  sym_generic_type = 42,
  sym_type_arguments = 43,
  sym_nested_struct = 44,
  sym_spread_type = 45,
  sym_attribute = 46,
  sym_comment = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_import_statement_repeat1 = 49,
  aux_sym_path_body_repeat1 = 50,
  aux_sym_enum_declaration_repeat1 = 51,
  aux_sym_variant_params_repeat1 = 52,
  aux_sym_struct_body_repeat1 = 53,
  aux_sym_type_arguments_repeat1 = 54,
  aux_sym_attribute_repeat1 = 55,
  alias_sym_imported_name = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_import] = "import",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [sym_path_relative_prefix] = "path_relative_prefix",
  [anon_sym_SLASH] = "/",
  [sym_path_segment] = "path_segment",
  [anon_sym_enum] = "enum",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_maybe] = "maybe",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT_DOT_DOT] = "...",
  [sym_attribute_arg] = "attribute_arg",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_string] = "string",
  [sym_type_identifier] = "type_identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_import_statement] = "import_statement",
  [sym_import_path] = "import_path",
  [sym_path_alias_prefix] = "path_alias_prefix",
  [sym_path_body] = "path_body",
  [sym_enum_declaration] = "enum_declaration",
  [sym_variant] = "variant",
  [sym_variant_params] = "variant_params",
  [sym_named_field] = "named_field",
  [sym_struct_declaration] = "struct_declaration",
  [sym_struct_body] = "struct_body",
  [sym_struct_field] = "struct_field",
  [sym__type] = "_type",
  [sym_maybe_type] = "maybe_type",
  [sym_generic_type] = "generic_type",
  [sym_type_arguments] = "type_arguments",
  [sym_nested_struct] = "nested_struct",
  [sym_spread_type] = "spread_type",
  [sym_attribute] = "attribute",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_statement_repeat1] = "import_statement_repeat1",
  [aux_sym_path_body_repeat1] = "path_body_repeat1",
  [aux_sym_enum_declaration_repeat1] = "enum_declaration_repeat1",
  [aux_sym_variant_params_repeat1] = "variant_params_repeat1",
  [aux_sym_struct_body_repeat1] = "struct_body_repeat1",
  [aux_sym_type_arguments_repeat1] = "type_arguments_repeat1",
  [aux_sym_attribute_repeat1] = "attribute_repeat1",
  [alias_sym_imported_name] = "imported_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_path_relative_prefix] = sym_path_relative_prefix,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_path_segment] = sym_path_segment,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_maybe] = anon_sym_maybe,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [sym_attribute_arg] = sym_attribute_arg,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_string] = sym_string,
  [sym_type_identifier] = sym_type_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_import_statement] = sym_import_statement,
  [sym_import_path] = sym_import_path,
  [sym_path_alias_prefix] = sym_path_alias_prefix,
  [sym_path_body] = sym_path_body,
  [sym_enum_declaration] = sym_enum_declaration,
  [sym_variant] = sym_variant,
  [sym_variant_params] = sym_variant_params,
  [sym_named_field] = sym_named_field,
  [sym_struct_declaration] = sym_struct_declaration,
  [sym_struct_body] = sym_struct_body,
  [sym_struct_field] = sym_struct_field,
  [sym__type] = sym__type,
  [sym_maybe_type] = sym_maybe_type,
  [sym_generic_type] = sym_generic_type,
  [sym_type_arguments] = sym_type_arguments,
  [sym_nested_struct] = sym_nested_struct,
  [sym_spread_type] = sym_spread_type,
  [sym_attribute] = sym_attribute,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_statement_repeat1] = aux_sym_import_statement_repeat1,
  [aux_sym_path_body_repeat1] = aux_sym_path_body_repeat1,
  [aux_sym_enum_declaration_repeat1] = aux_sym_enum_declaration_repeat1,
  [aux_sym_variant_params_repeat1] = aux_sym_variant_params_repeat1,
  [aux_sym_struct_body_repeat1] = aux_sym_struct_body_repeat1,
  [aux_sym_type_arguments_repeat1] = aux_sym_type_arguments_repeat1,
  [aux_sym_attribute_repeat1] = aux_sym_attribute_repeat1,
  [alias_sym_imported_name] = alias_sym_imported_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_path_relative_prefix] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_path_segment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_maybe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_path] = {
    .visible = true,
    .named = true,
  },
  [sym_path_alias_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_path_body] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_variant_params] = {
    .visible = true,
    .named = true,
  },
  [sym_named_field] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_maybe_type] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_spread_type] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variant_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_imported_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_path = 2,
  field_type = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_imported_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 33,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 33,
  [56] = 7,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 27,
  [68] = 68,
  [69] = 17,
  [70] = 70,
  [71] = 71,
  [72] = 26,
  [73] = 23,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 81,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 80,
  [94] = 82,
  [95] = 83,
  [96] = 84,
  [97] = 87,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '"', 74,
        '#', 33,
        '\'', 75,
        '(', 57,
        ')', 58,
        ',', 31,
        '.', 37,
        '/', 38,
        ':', 60,
        '<', 64,
        '>', 65,
        'e', 79,
        'i', 77,
        's', 84,
        '{', 30,
        '|', 56,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '#', 33,
        '(', 57,
        ')', 58,
        ',', 31,
        '.', 6,
        '/', 7,
        ':', 59,
        '<', 64,
        '>', 65,
        '{', 30,
        '|', 56,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '\'') ADVANCE(75);
      if (lookahead == ')') ADVANCE(58);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(66);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(53);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '#', 33,
        '(', 57,
        ',', 31,
        '/', 38,
        ':', 8,
        'e', 12,
        'i', 10,
        's', 17,
        '{', 30,
        '|', 56,
        '}', 32,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(22);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '#', 33,
        '/', 38,
        ':', 8,
        'e', 42,
        'i', 40,
        's', 47,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_import);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(66);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(34);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_path_relative_prefix);
      if (lookahead == '.') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'c') ADVANCE(49);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'm') ADVANCE(44);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'm') ADVANCE(55);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'n') ADVANCE(51);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'o') ADVANCE(45);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'p') ADVANCE(43);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'r') ADVANCE(48);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(46);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'u') ADVANCE(39);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'u') ADVANCE(41);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_enum);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_enum);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(29);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_struct);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_attribute_arg);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'm') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'y') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_maybe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 22},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 22},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 22},
  [52] = {.lex_state = 22},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 22},
  [59] = {.lex_state = 22},
  [60] = {.lex_state = 22},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 22},
  [64] = {.lex_state = 22},
  [65] = {.lex_state = 22},
  [66] = {.lex_state = 22},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 22},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 22},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 4},
  [112] = {.lex_state = 4},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 70},
  [115] = {.lex_state = 2},
  [116] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_path_relative_prefix] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_maybe] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(110),
    [sym__definition] = STATE(59),
    [sym_import_statement] = STATE(64),
    [sym_enum_declaration] = STATE(64),
    [sym_struct_declaration] = STATE(64),
    [sym_attribute] = STATE(64),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(13),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      aux_sym_source_file_token1,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(59), 1,
      sym__definition,
    STATE(64), 4,
      sym_import_statement,
      sym_enum_declaration,
      sym_struct_declaration,
      sym_attribute,
  [37] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      aux_sym_source_file_token1,
    ACTIONS(24), 1,
      anon_sym_import,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(30), 1,
      anon_sym_enum,
    ACTIONS(33), 1,
      anon_sym_struct,
    STATE(59), 1,
      sym__definition,
    STATE(3), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(64), 4,
      sym_import_statement,
      sym_enum_declaration,
      sym_struct_declaration,
      sym_attribute,
  [72] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 1,
      anon_sym_maybe,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(4), 1,
      sym_comment,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
    STATE(92), 3,
      sym_named_field,
      sym__type,
      sym_spread_type,
  [107] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_maybe,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(46), 1,
      sym_type_identifier,
    STATE(5), 1,
      sym_comment,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
    STATE(104), 3,
      sym_named_field,
      sym__type,
      sym_spread_type,
  [139] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(54), 1,
      anon_sym_POUND,
    STATE(6), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(50), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(61), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [170] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    STATE(7), 1,
      sym_comment,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [191] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(50), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(61), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [222] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_import_statement_repeat1,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(66), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    ACTIONS(68), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [251] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_struct_body_repeat1,
    ACTIONS(50), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(61), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [282] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_import_statement_repeat1,
    ACTIONS(66), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(76), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [311] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(86), 1,
      sym_path_segment,
    STATE(12), 1,
      sym_comment,
    STATE(46), 1,
      sym_path_body,
    ACTIONS(82), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
  [338] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      anon_sym_POUND,
    ACTIONS(99), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(91), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(13), 2,
      sym_comment,
      aux_sym_struct_body_repeat1,
    STATE(61), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [367] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(107), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(14), 2,
      sym_comment,
      aux_sym_import_statement_repeat1,
    ACTIONS(102), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUND,
    ACTIONS(110), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [392] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(44), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_struct_body_repeat1,
    STATE(15), 1,
      sym_comment,
    ACTIONS(50), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(61), 3,
      sym_struct_field,
      sym_spread_type,
      sym_attribute,
  [423] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(116), 1,
      anon_sym_LT,
    STATE(16), 1,
      sym_comment,
    STATE(38), 1,
      sym_type_arguments,
    ACTIONS(114), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [446] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [464] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(122), 1,
      anon_sym_SLASH,
    STATE(18), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_path_body_repeat1,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [486] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    STATE(19), 2,
      sym_comment,
      aux_sym_path_body_repeat1,
    ACTIONS(124), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [506] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(131), 4,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
  [526] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(135), 4,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
  [546] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(122), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      aux_sym_path_body_repeat1,
    STATE(22), 1,
      sym_comment,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [568] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(137), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [586] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(122), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      aux_sym_path_body_repeat1,
    STATE(24), 1,
      sym_comment,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [608] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(122), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      aux_sym_path_body_repeat1,
    STATE(25), 1,
      sym_comment,
    ACTIONS(141), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [630] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [648] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(145), 9,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_PIPE,
      anon_sym_struct,
  [666] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
    ACTIONS(149), 5,
      anon_sym_import,
      anon_sym_SLASH,
      sym_path_segment,
      anon_sym_enum,
      anon_sym_struct,
  [686] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_POUND,
    ACTIONS(159), 1,
      anon_sym_PIPE,
    ACTIONS(151), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(29), 2,
      sym_comment,
      aux_sym_enum_declaration_repeat1,
    STATE(78), 2,
      sym_variant,
      sym_attribute,
  [711] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(162), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(124), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [730] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    ACTIONS(168), 1,
      anon_sym_POUND,
    ACTIONS(170), 1,
      anon_sym_PIPE,
    STATE(31), 1,
      sym_comment,
    STATE(35), 1,
      aux_sym_enum_declaration_repeat1,
    ACTIONS(164), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(78), 2,
      sym_variant,
      sym_attribute,
  [757] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(168), 1,
      anon_sym_POUND,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_comment,
    STATE(71), 1,
      sym_variant_params,
    STATE(79), 1,
      sym_attribute,
    ACTIONS(172), 4,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [782] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_comment,
    ACTIONS(176), 3,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_POUND,
    ACTIONS(180), 3,
      anon_sym_import,
      anon_sym_enum,
      anon_sym_struct,
  [805] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(114), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [822] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(168), 1,
      anon_sym_POUND,
    ACTIONS(170), 1,
      anon_sym_PIPE,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym_enum_declaration_repeat1,
    STATE(35), 1,
      sym_comment,
    ACTIONS(164), 2,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
    STATE(78), 2,
      sym_variant,
      sym_attribute,
  [849] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(186), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [866] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(188), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [883] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(190), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [900] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(192), 1,
      anon_sym_maybe,
    ACTIONS(194), 1,
      anon_sym_GT,
    STATE(39), 1,
      sym_comment,
    STATE(89), 1,
      sym__type,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [927] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(196), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [944] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(41), 1,
      sym_comment,
    ACTIONS(198), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [961] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(42), 1,
      sym_comment,
    ACTIONS(200), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [978] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(43), 1,
      sym_comment,
    ACTIONS(202), 8,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [995] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(192), 1,
      anon_sym_maybe,
    STATE(44), 1,
      sym_comment,
    STATE(57), 1,
      sym__type,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1019] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(204), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_LPAREN,
    STATE(45), 1,
      sym_comment,
    ACTIONS(176), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
  [1039] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(208), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1055] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(47), 1,
      sym_comment,
    ACTIONS(210), 7,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1071] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_comment,
    ACTIONS(212), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1089] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(216), 1,
      anon_sym_POUND,
    ACTIONS(218), 1,
      sym_path_relative_prefix,
    ACTIONS(220), 1,
      sym_path_segment,
    STATE(12), 1,
      sym_path_alias_prefix,
    STATE(49), 1,
      sym_comment,
    STATE(51), 1,
      sym_import_path,
    STATE(52), 1,
      sym_path_body,
  [1117] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(192), 1,
      anon_sym_maybe,
    STATE(36), 1,
      sym__type,
    STATE(50), 1,
      sym_comment,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1141] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(224), 1,
      anon_sym_COLON_COLON,
    STATE(51), 1,
      sym_comment,
    ACTIONS(222), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1159] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_COLON_COLON,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1175] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(192), 1,
      anon_sym_maybe,
    STATE(53), 1,
      sym_comment,
    STATE(100), 1,
      sym__type,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1199] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym_type_identifier,
    ACTIONS(192), 1,
      anon_sym_maybe,
    STATE(54), 1,
      sym_comment,
    STATE(99), 1,
      sym__type,
    STATE(34), 3,
      sym_maybe_type,
      sym_generic_type,
      sym_nested_struct,
  [1223] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    ACTIONS(226), 1,
      sym_identifier,
    STATE(55), 1,
      sym_comment,
    ACTIONS(176), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1243] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(228), 1,
      anon_sym_LPAREN,
    STATE(56), 1,
      sym_comment,
    ACTIONS(56), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1261] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    STATE(57), 1,
      sym_comment,
    STATE(62), 1,
      sym_attribute,
    ACTIONS(230), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1281] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(232), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1296] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(234), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1311] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(236), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1326] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(238), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1341] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(240), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1356] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(74), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1371] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(242), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1386] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(244), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1401] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(66), 1,
      sym_comment,
    ACTIONS(246), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1416] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(67), 1,
      sym_comment,
    ACTIONS(145), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1431] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(248), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1446] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(118), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1461] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(70), 1,
      sym_comment,
    ACTIONS(250), 6,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_import,
      anon_sym_POUND,
      anon_sym_enum,
      anon_sym_struct,
  [1476] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(168), 1,
      anon_sym_POUND,
    STATE(71), 1,
      sym_comment,
    STATE(74), 1,
      sym_attribute,
    ACTIONS(252), 4,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [1495] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(72), 1,
      sym_comment,
    ACTIONS(143), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1510] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(73), 1,
      sym_comment,
    ACTIONS(137), 6,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT_DOT_DOT,
      sym_identifier,
  [1525] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(74), 1,
      sym_comment,
    ACTIONS(254), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1539] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(75), 1,
      sym_comment,
    ACTIONS(256), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1553] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(76), 1,
      sym_comment,
    ACTIONS(258), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1567] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(77), 1,
      sym_comment,
    ACTIONS(260), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1581] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(78), 1,
      sym_comment,
    ACTIONS(262), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1595] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(79), 1,
      sym_comment,
    ACTIONS(252), 5,
      aux_sym_source_file_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PIPE,
  [1609] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_comment,
    ACTIONS(266), 2,
      sym_attribute_arg,
      sym_string,
  [1623] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_attribute_repeat1,
  [1639] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_comment,
    STATE(84), 1,
      aux_sym_attribute_repeat1,
  [1655] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      sym_comment,
    ACTIONS(274), 2,
      sym_attribute_arg,
      sym_string,
  [1669] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_attribute_repeat1,
  [1685] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(85), 2,
      sym_comment,
      aux_sym_attribute_repeat1,
  [1699] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_comment,
    STATE(98), 1,
      aux_sym_variant_params_repeat1,
  [1715] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      sym_comment,
    STATE(88), 1,
      aux_sym_attribute_repeat1,
  [1731] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_attribute_repeat1,
    STATE(88), 1,
      sym_comment,
  [1747] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_GT,
    STATE(89), 1,
      sym_comment,
    STATE(90), 1,
      aux_sym_type_arguments_repeat1,
  [1763] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_GT,
    STATE(90), 1,
      sym_comment,
    STATE(91), 1,
      aux_sym_type_arguments_repeat1,
  [1779] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    ACTIONS(298), 1,
      anon_sym_GT,
    STATE(91), 2,
      sym_comment,
      aux_sym_type_arguments_repeat1,
  [1793] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_variant_params_repeat1,
    STATE(92), 1,
      sym_comment,
  [1809] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_comment,
    ACTIONS(304), 2,
      sym_attribute_arg,
      sym_string,
  [1823] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      sym_comment,
    STATE(96), 1,
      aux_sym_attribute_repeat1,
  [1839] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_comment,
    ACTIONS(308), 2,
      sym_attribute_arg,
      sym_string,
  [1853] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_attribute_repeat1,
    STATE(96), 1,
      sym_comment,
  [1869] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_attribute_repeat1,
    STATE(97), 1,
      sym_comment,
  [1885] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(312), 1,
      anon_sym_COMMA,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    STATE(98), 2,
      sym_comment,
      aux_sym_variant_params_repeat1,
  [1899] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(99), 1,
      sym_comment,
    ACTIONS(298), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1910] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(100), 1,
      sym_comment,
    ACTIONS(317), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1921] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(101), 1,
      sym_comment,
    ACTIONS(319), 2,
      sym_attribute_arg,
      sym_string,
  [1932] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(102), 1,
      sym_comment,
    ACTIONS(281), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1943] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(321), 1,
      anon_sym_LBRACE,
    STATE(60), 1,
      sym_struct_body,
    STATE(103), 1,
      sym_comment,
  [1956] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(104), 1,
      sym_comment,
    ACTIONS(315), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1967] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(323), 1,
      sym_type_identifier,
    STATE(105), 1,
      sym_comment,
  [1977] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(325), 1,
      sym_type_identifier,
    STATE(106), 1,
      sym_comment,
  [1987] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(327), 1,
      anon_sym_COLON,
    STATE(107), 1,
      sym_comment,
  [1997] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(329), 1,
      anon_sym_LBRACE,
    STATE(108), 1,
      sym_comment,
  [2007] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(331), 1,
      sym_type_identifier,
    STATE(109), 1,
      sym_comment,
  [2017] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
    STATE(110), 1,
      sym_comment,
  [2027] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(335), 1,
      sym_path_segment,
    STATE(111), 1,
      sym_comment,
  [2037] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(337), 1,
      sym_path_segment,
    STATE(112), 1,
      sym_comment,
  [2047] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(339), 1,
      sym_type_identifier,
    STATE(113), 1,
      sym_comment,
  [2057] = 3,
    ACTIONS(341), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(343), 1,
      aux_sym_comment_token1,
    STATE(114), 1,
      sym_comment,
  [2067] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(345), 1,
      anon_sym_COLON,
    STATE(115), 1,
      sym_comment,
  [2077] = 1,
    ACTIONS(347), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 191,
  [SMALL_STATE(9)] = 222,
  [SMALL_STATE(10)] = 251,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 311,
  [SMALL_STATE(13)] = 338,
  [SMALL_STATE(14)] = 367,
  [SMALL_STATE(15)] = 392,
  [SMALL_STATE(16)] = 423,
  [SMALL_STATE(17)] = 446,
  [SMALL_STATE(18)] = 464,
  [SMALL_STATE(19)] = 486,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 526,
  [SMALL_STATE(22)] = 546,
  [SMALL_STATE(23)] = 568,
  [SMALL_STATE(24)] = 586,
  [SMALL_STATE(25)] = 608,
  [SMALL_STATE(26)] = 630,
  [SMALL_STATE(27)] = 648,
  [SMALL_STATE(28)] = 666,
  [SMALL_STATE(29)] = 686,
  [SMALL_STATE(30)] = 711,
  [SMALL_STATE(31)] = 730,
  [SMALL_STATE(32)] = 757,
  [SMALL_STATE(33)] = 782,
  [SMALL_STATE(34)] = 805,
  [SMALL_STATE(35)] = 822,
  [SMALL_STATE(36)] = 849,
  [SMALL_STATE(37)] = 866,
  [SMALL_STATE(38)] = 883,
  [SMALL_STATE(39)] = 900,
  [SMALL_STATE(40)] = 927,
  [SMALL_STATE(41)] = 944,
  [SMALL_STATE(42)] = 961,
  [SMALL_STATE(43)] = 978,
  [SMALL_STATE(44)] = 995,
  [SMALL_STATE(45)] = 1019,
  [SMALL_STATE(46)] = 1039,
  [SMALL_STATE(47)] = 1055,
  [SMALL_STATE(48)] = 1071,
  [SMALL_STATE(49)] = 1089,
  [SMALL_STATE(50)] = 1117,
  [SMALL_STATE(51)] = 1141,
  [SMALL_STATE(52)] = 1159,
  [SMALL_STATE(53)] = 1175,
  [SMALL_STATE(54)] = 1199,
  [SMALL_STATE(55)] = 1223,
  [SMALL_STATE(56)] = 1243,
  [SMALL_STATE(57)] = 1261,
  [SMALL_STATE(58)] = 1281,
  [SMALL_STATE(59)] = 1296,
  [SMALL_STATE(60)] = 1311,
  [SMALL_STATE(61)] = 1326,
  [SMALL_STATE(62)] = 1341,
  [SMALL_STATE(63)] = 1356,
  [SMALL_STATE(64)] = 1371,
  [SMALL_STATE(65)] = 1386,
  [SMALL_STATE(66)] = 1401,
  [SMALL_STATE(67)] = 1416,
  [SMALL_STATE(68)] = 1431,
  [SMALL_STATE(69)] = 1446,
  [SMALL_STATE(70)] = 1461,
  [SMALL_STATE(71)] = 1476,
  [SMALL_STATE(72)] = 1495,
  [SMALL_STATE(73)] = 1510,
  [SMALL_STATE(74)] = 1525,
  [SMALL_STATE(75)] = 1539,
  [SMALL_STATE(76)] = 1553,
  [SMALL_STATE(77)] = 1567,
  [SMALL_STATE(78)] = 1581,
  [SMALL_STATE(79)] = 1595,
  [SMALL_STATE(80)] = 1609,
  [SMALL_STATE(81)] = 1623,
  [SMALL_STATE(82)] = 1639,
  [SMALL_STATE(83)] = 1655,
  [SMALL_STATE(84)] = 1669,
  [SMALL_STATE(85)] = 1685,
  [SMALL_STATE(86)] = 1699,
  [SMALL_STATE(87)] = 1715,
  [SMALL_STATE(88)] = 1731,
  [SMALL_STATE(89)] = 1747,
  [SMALL_STATE(90)] = 1763,
  [SMALL_STATE(91)] = 1779,
  [SMALL_STATE(92)] = 1793,
  [SMALL_STATE(93)] = 1809,
  [SMALL_STATE(94)] = 1823,
  [SMALL_STATE(95)] = 1839,
  [SMALL_STATE(96)] = 1853,
  [SMALL_STATE(97)] = 1869,
  [SMALL_STATE(98)] = 1885,
  [SMALL_STATE(99)] = 1899,
  [SMALL_STATE(100)] = 1910,
  [SMALL_STATE(101)] = 1921,
  [SMALL_STATE(102)] = 1932,
  [SMALL_STATE(103)] = 1943,
  [SMALL_STATE(104)] = 1956,
  [SMALL_STATE(105)] = 1967,
  [SMALL_STATE(106)] = 1977,
  [SMALL_STATE(107)] = 1987,
  [SMALL_STATE(108)] = 1997,
  [SMALL_STATE(109)] = 2007,
  [SMALL_STATE(110)] = 2017,
  [SMALL_STATE(111)] = 2027,
  [SMALL_STATE(112)] = 2037,
  [SMALL_STATE(113)] = 2047,
  [SMALL_STATE(114)] = 2057,
  [SMALL_STATE(115)] = 2067,
  [SMALL_STATE(116)] = 2077,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 4, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_path, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_path, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_body, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_body_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_body_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_import_statement_repeat1, 1, 0, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 6, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_body, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_body, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_alias_prefix, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_alias_prefix, 1, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_path_body_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 2, 0, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_maybe_type, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_struct, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, 0, 5),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_struct, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 4, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_path, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread_type, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 2, 0, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 4),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_declaration, 3, 0, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, 0, 4),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 3, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_declaration, 4, 0, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_declaration, 5, 0, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 3, 0, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant, 4, 0, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 3, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_params, 4, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_declaration_repeat1, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_repeat1, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_arguments_repeat1, 2, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [312] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variant_params_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variant_params_repeat1, 2, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_field, 3, 0, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [333] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [343] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lume(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lume",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
